linters-settings:
  staticcheck:
    checks: [
      "all",
      "-SA1019" # There are valid use cases of strings.Title
    ]
  nakedret:
    max-func-lines: 0 # Disallow any unnamed return statement
  govet:
    settings:
      printf: # The name of the analyzer, run `go tool vet help` to see all analyzers
        funcs: # Run `go tool vet help printf` to see all options of `printf`
          - (unknwon.dev/clog/v2).Trace
          - (unknwon.dev/clog/v2).Info
          - (unknwon.dev/clog/v2).Warn
          - (unknwon.dev/clog/v2).Error
          - (unknwon.dev/clog/v2).ErrorDepth
          - (unknwon.dev/clog/v2).Fatal
          - (unknwon.dev/clog/v2).FatalDepth

linters:
  enable:
    - unused
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - nakedret
    - gofmt
    - rowserrcheck
    - unconvert
    - goimports
    - unparam
